export enum AuthoringCommittee {
    'Committee on Constitutional Affairs' = 'Constitutional Affairs',   
    'Foreign Affairs' = 'Foreign Affairs',
    'Committee on Agriculture and Rural Development' = 'Agriculture and Rural Development',
    'Committee on Budgets' = 'Budgets',
    'Committee on Budgetary Control' = 'Budgetary Control',
    'Committee on Culture and Education' = 'Culture and Education',
    'Committee on Development' = 'Development',
    'Committee on Economic and Monetary Affairs' = 'Economic and Monetary Affairs',
    'Committee on Employment and Social Affairs' = 'Employment and Social Affairs',
    'Committee on Environment, Public Health and Food Safety' = 'Environment, Public Health and Food Safety',
    'Committee on Women’s Rights and Gender Equality' = 'Women’s Rights and Gender Equality',
    'Committee on Civil Liberties, Justice and Home Affairs' = 'Civil Liberties, Justice and Home Affairs',
    'Joint ENVI - ITRE' = 'Joint ENVI - ITRE',
    'Joint IMCO - JURI' = 'Joint IMCO - JURI',
    'Joint AFET - DEVE' = 'Joint AFET - DEVE',
    'Joint JURI - LIBE' = 'Joint JURI - LIBE',
    'Joint FEMM - LIBE' = 'Joint FEMM - LIBE',
    }