export enum OutputLanguage {
    BG = "BG - български",
    ES = "ES - español",
    CS = "CS - čeština",
    DA = "DA - dansk",
    DE = "DE - Deutsch",
    ET = "ET - eesti keel",
    EL = "EL - ελληνικά",
    EN = "EN - English",
    FR = "FR - français",
    GA = "GA - Gaeilge",
    HR = "HR - hrvatski",
    IT = "IT - italiano",
    LV = "LV - latviešu valoda",
    LT = "LT - lietuvių kalba",
    HU = "HU - magyar",
    MT = "MT - Malti",
    NL = "NL - Nederlands",
    PL = "PL - polski",
    PT = "PT - português",
    RO = "RO - română",
    SK = "SK - slovenčina",
    SL = "SL - slovenščina",
    FI = "FI - suomi",
    SV = "SV - svenska",
    XM = "XM - Multi languages"
}